### ISSUE TITLE
Yellow strip

### ISSUE THREAD

**Issue by CoSandu** [ITHACA-org/drought#2]
Dears, I've noticed that at 2000km graphic scale on the east of Africa a yellow strip appears. See the image below (the strip is highlighted in red). 
Buone Feste!
Consta
![cattura](https://cloud.githubusercontent.com/assets/15925802/12053474/daeaaf4e-af19-11e5-92cc-e4786ae83152.PNG)

**Comment by sbsimo** [comment]
The yellow stripe is an artefact created by GeoServer when reprojecting the original data (in LL WGS84) into Google Mercator projection. It affects only that zoom level.

We can consider using another projection for our application, as soon as a new basemap layer will be chosen.

**Comment by CoSandu** [comment]
Thank you very much for the explanation. Let's hope that with when a new projection and a new basemap aree available we will no longer see the strip.

**Comment by sbsimo** [comment]
zoom level blocked to level 8 --> the yellow stripe is not visible anymore
